const redux = require("redux");
const Product = [
/* category Featured*/
{
    id: 1,
    name: "Featured Beauty Women Clothing White",
    category: "Featured",
    price: 410,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, Summer and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 2,
    name: "Featured Black Sporting Leggings",
    category: "Featured",
    price: 195,
    sale__off: "30%",
    best__sell: false,
    main__image: require("../Assets/images/products/Featured/Featured Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Black Sporting Leggings/side5.jpg")
    ],
    color: "orange",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 3,
    name: "Featured Cool Women Casual",
    category: "Featured",
    price: 340,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Featured/Featured Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Cool Women Casual/side5.jpg")
    ],
    color: "orange",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 4,
    name: "Featured Fashion For Female High",
    category: "Featured",
    price: 200,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Featured/Featured Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion For Female High/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 5,
    name: "Featured Fashion Women Digital",
    category: "Featured",
    price: 270,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Featured/Featured Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Fashion Women Digital/side5.jpg")
    ],
    color: "blue",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 6,
    name: "Featured Women Print Fashion Low",
    category: "Featured",
    price: 240,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Featured/Featured Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Featured/Featured Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Featured/Featured Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Featured/Featured Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Featured/Featured Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Featured/Featured Women Print Fashion Low/side5.jpg")
    ],
    color: "pink",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Featured*/
/* category Hot*/
{
    id: 7,
    name: "Hot Beauty Women Clothing White",
    category: "Hot",
    price: 300,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 8,
    name: "Hot Black Sporting Leggings",
    category: "Hot",
    price: 290,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Hot/Hot Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Black Sporting Leggings/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 9,
    name: "Hot Cool Women Casual",
    category: "Hot",
    price: 280,
    sale__off: "20%",
    best__sell: false,
    main__image: require("../Assets/images/products/Hot/Hot Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Cool Women Casual/side5.jpg")
    ],
    color: "red",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 10,
    name: "Hot Fashion For Female High",
    category: "Hot",
    price: 220,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Hot/Hot Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion For Female High/side5.jpg")
    ],
    color: "pink",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 11,
    name: "Hot Fashion Women Digital",
    category: "Hot",
    price: 260,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Hot/Hot Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Fashion Women Digital/side5.jpg")
    ],
    color: "pink",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 12,
    name: "Hot Women Print Fashion Low",
    category: "Hot",
    price: 250,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Hot/Hot Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Hot/Hot Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Hot/Hot Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Hot/Hot Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Hot/Hot Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Hot/Hot Women Print Fashion Low/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Hot*/
/* category Latest*/
{
    id: 13,
    name: "Latest Beauty Women Clothing White",
    category: "Latest",
    price: 395,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 14,
    name: "Latest Black Sporting Leggings",
    category: "Latest",
    price: 385,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Latest/Latest Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Black Sporting Leggings/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 15,
    name: "Latest Cool Women Casual",
    category: "Latest",
    price: 375,
    sale__off: "10%",
    best__sell: false,
    main__image: require("../Assets/images/products/Latest/Latest Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Cool Women Casual/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 16,
    name: "Latest Fashion For Female High",
    category: "Latest",
    price: 365,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Latest/Latest Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion For Female High/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 17,
    name: "Latest Fashion Women Digital",
    category: "Latest",
    price: 355,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Latest/Latest Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Fashion Women Digital/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 18,
    name: "Latest Women Print Fashion Low",
    category: "Latest",
    price: 345,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Latest/Latest Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Latest/Latest Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Latest/Latest Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Latest/Latest Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Latest/Latest Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Latest/Latest Women Print Fashion Low/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Latest*/
/* category Minimal*/
{
    id: 19,
    name: "Minimal Beauty Women Clothing White",
    category: "Minimal",
    price: 392,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 20,
    name: "Minimal Black Sporting Leggings",
    category: "Minimal",
    price: 382,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Black Sporting Leggings/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 21,
    name: "Minimal Cool Women Casual",
    category: "Minimal",
    price: 372,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Minimal/Minimal Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Cool Women Casual/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 22,
    name: "Minimal Fashion For Female High",
    category: "Minimal",
    price: 362,
    sale__off: "20%",
    best__sell: false,
    main__image: require("../Assets/images/products/Minimal/Minimal Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion For Female High/side5.jpg")
    ],
    color: "orange",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 23,
    name: "Minimal Fashion Women Digital",
    category: "Minimal",
    price: 352,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Fashion Women Digital/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 24,
    name: "Minimal Women Print Fashion Low",
    category: "Minimal",
    price: 342,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Minimal/Minimal Women Print Fashion Low/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Minimal*/
/* category Modern*/
{
    id: 25,
    name: "Modern Beauty Women Clothing White",
    category: "Modern",
    price: 295,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 26,
    name: "Modern Black Sporting Leggings",
    category: "Modern",
    price: 285,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Modern/Modern Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Black Sporting Leggings/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 27,
    name: "Modern Cool Women Casual",
    category: "Modern",
    price: 315,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Modern/Modern Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Cool Women Casual/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 28,
    name: "Modern Fashion For Female High",
    category: "Modern",
    price: 325,
    sale__off: "30%",
    best__sell: false,
    main__image: require("../Assets/images/products/Modern/Modern Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion For Female High/side5.jpg")
    ],
    color: "yellow",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 29,
    name: "Modern Fashion Women Digital",
    category: "Modern",
    price: 335,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Modern/Modern Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Fashion Women Digital/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 30,
    name: "Modern Women Print Fashion Low",
    category: "Modern",
    price: 305,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Modern/Modern Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Modern/Modern Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Modern/Modern Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Modern/Modern Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Modern/Modern Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Modern/Modern Women Print Fashion Low/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Modern*/
/* category Summer*/
{
    id: 31,
    name: "Summer Beauty Women Clothing White",
    category: "Summer",
    price: 250,
    sale__off: false,
    best__sell: true,
    main__image: require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Beauty Women Clothing White/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, Summer and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 32,
    name: "Summer Black Sporting Leggings",
    category: "Summer",
    price: 210,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Summer/Summer Black Sporting Leggings/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Black Sporting Leggings/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Black Sporting Leggings/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Black Sporting Leggings/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Black Sporting Leggings/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Black Sporting Leggings/side5.jpg")
    ],
    color: "black",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, Summer and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 33,
    name: "Summer Cool Women Casual",
    category: "Summer",
    price: 230,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Summer/Summer Cool Women Casual/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Cool Women Casual/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Cool Women Casual/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Cool Women Casual/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Cool Women Casual/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Cool Women Casual/side5.jpg")
    ],
    color: "blue",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, Summer and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 34,
    name: "Summer Fashion For Female High",
    category: "Summer",
    price: 225,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Summer/Summer Fashion For Female High/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Fashion For Female High/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion For Female High/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion For Female High/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion For Female High/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion For Female High/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, Summer and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 35,
    name: "Summer Fashion Women Digital",
    category: "Summer",
    price: 275,
    sale__off: false,
    best__sell: false,
    main__image: require("../Assets/images/products/Summer/Summer Fashion Women Digital/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Fashion Women Digital/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion Women Digital/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion Women Digital/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion Women Digital/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Fashion Women Digital/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
{
    id: 36,
    name: "Summer Women Print Fashion Low",
    category: "Summer",
    price: 279,
    sale__off: "30%",
    best__sell: false,
    main__image: require("../Assets/images/products/Summer/Summer Women Print Fashion Low/main/main.jpg"),
    slide__image: [
        require("../Assets/images/products/Summer/Summer Women Print Fashion Low/side1.jpg"),
        require("../Assets/images/products/Summer/Summer Women Print Fashion Low/side2.jpg"),
        require("../Assets/images/products/Summer/Summer Women Print Fashion Low/side3.jpg"),
        require("../Assets/images/products/Summer/Summer Women Print Fashion Low/side4.jpg"),
        require("../Assets/images/products/Summer/Summer Women Print Fashion Low/side5.jpg")
    ],
    color: "white",
    material: "cotton",
    description: "Fashion & Clothing Shopify Themes & TemplateOur Fashion shopify theme is a best, popular, modern and clean. Also the main specialty of our Shopify Theme is Advance Feature List. You can easily setup your store Because Our fashion shopify Theme have Advance Theme",
},
/* end category Summer*/
]
const reducer = (init = Product, action) => {
    return init;
}
const Store = redux.createStore(reducer);
console.log(Store.getState());
export default Store;